In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers
from transform_output_format import get_2D_output, get_4D_output

In [44]:
# Load data from raw_data
data = np.load('../raw_data/X_train_copernicus.npz', allow_pickle=True)
y_train = pd.read_csv('../raw_data/y_train.csv')

In [19]:
y_train.head()

   id_sequence       0       1       2  ...   10400   10401   10402   10403
0            0  247.51  261.68  260.16  ...  381.41  381.75  382.08  382.42
1            1  471.37  476.41  474.55  ...  503.60  503.98  504.37  504.75
2            2  458.39  463.38  461.54  ...  388.92  389.30  389.67  390.04
3            3  223.42  228.37  226.91  ...   93.97   94.21   94.45   94.69
4            4  170.23  137.61  136.96  ...  382.88  383.03  383.17  383.32

[5 rows x 10405 columns]

In [45]:
# converting into a matrix 
y_train = get_4D_output(y_train)
y_train.shape

(1845, 4, 51, 51)

In [4]:
# Extract features from data
GHI = data['GHI']
CLS = data['CLS']
SAA = data['SAA']
SZA = data['SZA']
DATE = data['datetime']

In [21]:
# Swap the axes representing the number of frames and number of data samples.
# Not applying IDK the reason of it 
#dataset = np.swapaxes(GHI, 0, 1)
# We'll pick out 1000 of the 1845 total examples and use those.
GHI_1000 = GHI[:1000, ...]
# Add a channel dimension since the images are grayscale.
GHI_1000 = np.expand_dims(GHI_1000, axis=-1)

In [46]:
# We'll pick out 1000 of the 1845 total examples and use those.
y_train_1000 = y_train[:1000, ...]
# Add a channel dimension since the images are grayscale.
y_train_1000 = np.expand_dims(y_train_1000, axis=-1)

In [47]:
y_train_1000.shape

(1000, 4, 51, 51, 1)

In [34]:
# Split into train and validation sets using indexing to optimize memory.
indexes = np.arange(GHI_1000.shape[0]) 
np.random.shuffle(indexes)
x_train_index = indexes[: int(0.9 * GHI_1000.shape[0])] # I want 90% of train and 10% validation
x_val_index = indexes[int(0.9 * GHI_1000.shape[0]) :] 
x_train = GHI_1000[x_train_index]
x_val = GHI_1000[x_train_index]

In [48]:
# Split into train and validation sets using indexing to optimize memory.
y_indexes = np.arange(y_train_1000.shape[0]) 
np.random.shuffle(y_indexes)
y_train_index = y_indexes[: int(0.9 * y_train_1000.shape[0])]
y_val_index = y_indexes[int(0.9 * y_train_1000.shape[0]) :] 
y_train = y_train_1000[y_train_index]
y_val = y_train_1000[y_train_index]

In [ ]:
# Normalize the data to the 0-1 range.
#train_dataset = train_dataset / 255
#val_dataset = val_dataset / 255
# not applying for now

In [31]:
# We'll define a helper function to shift the frames, where
# `x` is frames 0 to n - 1, and `y` is frames 1 to n.
#    def create_shifted_frames(data):
#            x = data[:, 0 : data.shape[1] - 1, :, :]
#            y = data[:, 1 : data.shape[1], :, :]
#            return x, y
# IDK if we need this I think our X_train are the 1st 4 timestamp and Y_test the last 4

In [ ]:
# Apply the processing function to the datasets.
# x_train, y_train = create_shifted_frames(train_dataset)
# x_val, y_val = create_shifted_frames(val_dataset)
# not applying either since we're not useing the above function

In [49]:
# Inspect the dataset.
print("Training Dataset Shapes: " + str(x_train.shape) + ", " + str(y_train.shape))
print("Validation Dataset Shapes: " + str(x_val.shape) + ", " + str(y_val.shape))

Training Dataset Shapes: (900, 4, 81, 81, 1), (900, 4, 51, 51, 1)
Validation Dataset Shapes: (900, 4, 81, 81, 1), (900, 4, 51, 51, 1)

In [ ]:
# reshaping x_train and x_val

## Model Construction